### Listar todos os livros
GET http://localhost:8080/books
Accept: application/json


### Adicionar um novo livro
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "Clean Architecture",
  "author": "Robert C. Martin",
  "genre": "Software Engineering"
}

### ler livros
POST http://localhost:8080/books/simulate-reading
Content-Type: application/json

["1","2","3","4"]

### Listar 1 livro especifico
GET http://localhost:8080/books/5
Accept: application/json

### Buscar Livros 
GET http://localhost:8080/books/search?name=Architecture
Accept: application/json

### Atualizar um livro existente
GET http://localhost:8080/books/2
Content-Type: application/json

{
  "title": "Clean Code",
  "author": "Robert C. Martin",
  "genre": "Software Development"
}

### Deletar um livro
DELETE http://localhost:8080/books/1